
export const construccion = [
  { text: "Ayudante de obra / peon de obra", value: 'Ayudante de obra/peon de obra' },
  { text: "Albañil - Caravistero-tabiquero", value: 'Albañil - Caravistero-tabiquero' },
  { text: "Alicatador solador", value: 'Alicatador solador' },
  { text: "Encofrador", value: 'Encofrador' },
  { text: "Ferralista", value: 'Ferralista' },
  { text: "Carpintero de madera", value: 'Carpintero de madera' },
  { text: "Cerrajero", value: 'Cerrajero' },
  { text: "Demolicion", value: 'Demolicion' },
  { text: "Techador", value: 'Techador' },
  { text: "Pintor", value: 'Pintor' },
  { text: "Cristalero", value: 'Cristalero' },
  { text: "Soldador", value: 'Soldador' },
  { text: "Chapista industrial", value: 'Chapista industrial' },
  { text: "Electricista", value: 'Electricista' },
  { text: "Fontanero (instalador de tuberías)", value: 'Fontanero' },
  { text: "Pulidor de suelos, terrazo, ladrillo, hormigón", value: 'Pulidor de suelos, terrazo, ladrillo, hormigón' },
  { text: "Gruista", value: 'Gruista' },
  { text: "Conductor de maquinaria", value: 'Conductor de maquinaria' },
  { text: "Colocador de prefabricados ligeros o de pavimientos ligeros", value: 'Colocador de prefabricados ligeros o de pavimientos ligeros' },
  { text: "Tallista (piedras, mármol)", value: 'Tallista' },
  { text: "Instalador de materiales de impermeabilización en edificios", value: 'Instalador de materiales de impermeabilización en edificios' },
  { text: "Instalador de gas", value: 'Instalador de gas' },
  { text: "Instalador de conducciones de calefacción y agua caliente sanitaria", value: 'Instalador de conducciones de calefacción y agua caliente sanitaria' },
  { text: "Jefe de obra", value: 'Jefe de obra' },
  { text: "Instalador de aislamiento de edificios", value: 'Instalador de aislamiento de edificios' },
];
export const gastronomy = [
  { text: "Jefe de cocina", value: 'Jefe de cocina' },
  { text: "Subjefe de cocina", value: 'Subjefe de cocina' },
  { text: "Gerente/coordinador de cocina", value: 'Gerente/coordinador de cocina' },
  { text: "Cocinero", value: 'Cocinero' },
  { text: "Ayudante de cocinero", value: 'Ayudante de cocinero' },
  { text: "Servicio de  limpieza", value: 'Servicio de  limpieza' },
 ];
 export const tiempo = [
  {text: "0 a 6 meses", value :'0 a 6 meses'},
  {text: "1 a 2 años", value :'1 a 2 años'},
  {text: "3 a 5 años", value :'3 a 5 años'},
  {text: "Más de 5 años", value :'Más de 5 años'},
 ]
 export const  pais= [     
  {text: "Cuba", value :'Cuba'}, 
  {text: "Argentina", value :'Argentina'},
  {text: "Brazil", value :'Brazil'},
  {text: "Colombia", value :'Colombia'},
  {text: "Paraguay", value :'Paraguay'},
  {text: "Venezuela", value :'Venezuela'},
  {text: "Perú", value :'Perú'},
  {text: "Uruguay ", value :'Uruguay'},
  {text: "México", value :'México'},
  {text: "Chile", value :'Chile'},
  {text: "Bolivia", value :'Bolivia'},
  {text: "Costa Rica", value :'Costa Rica'},
  {text: "Guatemala", value :'Guatemala'},
  {text: "Honduras", value :'Honduras'},
  {text: "Nicaragua", value :'Nicaragua'},
  {text: "Panamá", value :'Panamá'},
 ]

