export const construction = [
  { text: "Sin Especificar", value: '' },
  { text: "Ayudante de obra / peon de obra", value: 'Ayudante de obra/peon de obra' },
  { text: "Albañil - Caravistero-tabiquero", value: 'Albañil - Caravistero-tabiquero' },
  { text: "Alicatador solador", value: 'Alicatador solador' },
  { text: "Encofrador", value: 'Encofrador' },
  { text: "Ferralista", value: 'Ferralista' },
  { text: "Carpintero de madera", value: 'Carpintero de madera' },
  { text: "Cerrajero", value: 'Cerrajero' },
  { text: "Demolicion", value: 'Demolicion' },
  { text: "Techador", value: 'Techador' },
  { text: "Pintor", value: 'Pintor' },
  { text: "Cristalero", value: 'Cristalero' },
  { text: "Soldador", value: 'Soldador' },
  { text: "Chapista industrial", value: 'Chapista industrial' },
  { text: "Electricista", value: 'Electricista' },
  { text: "Fontanero (instalador de tuberías)", value: 'Fontanero' },
  { text: "Pulidor de suelos, terrazo, ladrillo, hormigón", value: 'Pulidor de suelos, terrazo, ladrillo, hormigón' },
  { text: "Gruista", value: 'Gruista' },
  { text: "Conductor de maquinaria", value: 'Conductor de maquinaria' },
  { text: "Colocador de prefabricados ligeros o de pavimientos ligeros", value: 'Colocador de prefabricados ligeros o de pavimientos ligeros' },
  { text: "Tallista (piedras, mármol)", value: 'Tallista' },
  { text: "Instalador de materiales de impermeabilización en edificios", value: 'Instalador de materiales de impermeabilización en edificios' },
  { text: "Instalador de gas", value: 'Instalador de gas' },
  { text: "Instalador de conducciones de calefacción y agua caliente sanitaria", value: 'Instalador de conducciones de calefacción y agua caliente sanitaria' },
  { text: "Jefe de obra", value: 'Jefe de obra' },
  { text: "Instalador de aislamiento de edificios", value: 'Instalador de aislamiento de edificios' },
];
export const gastronomy = [
  { text: "Jefe de cocina", value: null },
  { text: "Subjefe de cocina", value: 'Ayudante de obra/peon de obra' },
  { text: "Gerente/coordinador de cocina", value: 'Albañil - Caravistero-tabiquero' },
  { text: "Cocinero", value: 'Alicatador solador' },
  { text: "Ayudante de cocinero", value: 'Encofrador' },
  { text: "Servicio de  limpieza", value: 'Ferralista' },
 ];

